apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJnaGNyLmlvIjogewogICAgICAiYXV0aCI6ICJkbUZrWVdkaGJXRTZaMmwwYUhWaVgzQmhkRjh4TVVGTVRVYzNUMGt3VVVKTE1tbE1jRTVDYkVkSlgwaDNhSE5OVHpBMmNtOUpkVXhLVkdKaFlXTktZbHBMYXpoeVdUQnVWVFZ6YUROUWRYWk5RbWRaUkVkRlJqTXlSRE15U20xSlNHaHZkbnBPIgogICAgfQogIH0sCiAgImNyZWRzU3RvcmUiOiAiZGVza3RvcCIsCiAgImN1cnJlbnRDb250ZXh0IjogImRlc2t0b3AtbGludXgiCn0K
type: kubernetes.io/dockerconfigjson
